/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArcgisBasemapGallery {
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisBasemapToggle {
        "nextBasemap": string;
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisBookmarks {
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisCoordinateConversion {
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisDirections {
        "apiKey": string;
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisEditor {
        "allowedWorkflows": string;
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisExpand {
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisFeatureTable {
        "fieldConfigs": any | string;
        "itemId": string;
        "layer": any;
        "position": string;
        "url": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisLayerList {
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisLegend {
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisMap {
        "apiKey": string;
        "basemap": string;
        "center": number[] | string;
        "view": __esri.MapView;
        "zoom": number;
    }
    interface ArcgisPortal {
        "portal": any;
        "url": string;
    }
    interface ArcgisPrint {
        "allowedFormats": string;
        "allowedLayouts": string;
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisSearch {
        "position": string;
        "view": __esri.MapView | __esri.SceneView;
        "widget": any;
    }
    interface ArcgisWebmap {
        "apiKey": string;
        "center": number[] | string;
        "itemId": string;
        "view": __esri.MapView;
        "zoom": number;
    }
    interface ArcgisWebscene {
        "apiKey": string;
        "center": number[] | string;
        "itemId": string;
        "view": __esri.SceneView;
        "zoom": number;
    }
}
declare global {
    interface HTMLArcgisBasemapGalleryElement extends Components.ArcgisBasemapGallery, HTMLStencilElement {
    }
    var HTMLArcgisBasemapGalleryElement: {
        prototype: HTMLArcgisBasemapGalleryElement;
        new (): HTMLArcgisBasemapGalleryElement;
    };
    interface HTMLArcgisBasemapToggleElement extends Components.ArcgisBasemapToggle, HTMLStencilElement {
    }
    var HTMLArcgisBasemapToggleElement: {
        prototype: HTMLArcgisBasemapToggleElement;
        new (): HTMLArcgisBasemapToggleElement;
    };
    interface HTMLArcgisBookmarksElement extends Components.ArcgisBookmarks, HTMLStencilElement {
    }
    var HTMLArcgisBookmarksElement: {
        prototype: HTMLArcgisBookmarksElement;
        new (): HTMLArcgisBookmarksElement;
    };
    interface HTMLArcgisCoordinateConversionElement extends Components.ArcgisCoordinateConversion, HTMLStencilElement {
    }
    var HTMLArcgisCoordinateConversionElement: {
        prototype: HTMLArcgisCoordinateConversionElement;
        new (): HTMLArcgisCoordinateConversionElement;
    };
    interface HTMLArcgisDirectionsElement extends Components.ArcgisDirections, HTMLStencilElement {
    }
    var HTMLArcgisDirectionsElement: {
        prototype: HTMLArcgisDirectionsElement;
        new (): HTMLArcgisDirectionsElement;
    };
    interface HTMLArcgisEditorElement extends Components.ArcgisEditor, HTMLStencilElement {
    }
    var HTMLArcgisEditorElement: {
        prototype: HTMLArcgisEditorElement;
        new (): HTMLArcgisEditorElement;
    };
    interface HTMLArcgisExpandElement extends Components.ArcgisExpand, HTMLStencilElement {
    }
    var HTMLArcgisExpandElement: {
        prototype: HTMLArcgisExpandElement;
        new (): HTMLArcgisExpandElement;
    };
    interface HTMLArcgisFeatureTableElement extends Components.ArcgisFeatureTable, HTMLStencilElement {
    }
    var HTMLArcgisFeatureTableElement: {
        prototype: HTMLArcgisFeatureTableElement;
        new (): HTMLArcgisFeatureTableElement;
    };
    interface HTMLArcgisLayerListElement extends Components.ArcgisLayerList, HTMLStencilElement {
    }
    var HTMLArcgisLayerListElement: {
        prototype: HTMLArcgisLayerListElement;
        new (): HTMLArcgisLayerListElement;
    };
    interface HTMLArcgisLegendElement extends Components.ArcgisLegend, HTMLStencilElement {
    }
    var HTMLArcgisLegendElement: {
        prototype: HTMLArcgisLegendElement;
        new (): HTMLArcgisLegendElement;
    };
    interface HTMLArcgisMapElement extends Components.ArcgisMap, HTMLStencilElement {
    }
    var HTMLArcgisMapElement: {
        prototype: HTMLArcgisMapElement;
        new (): HTMLArcgisMapElement;
    };
    interface HTMLArcgisPortalElement extends Components.ArcgisPortal, HTMLStencilElement {
    }
    var HTMLArcgisPortalElement: {
        prototype: HTMLArcgisPortalElement;
        new (): HTMLArcgisPortalElement;
    };
    interface HTMLArcgisPrintElement extends Components.ArcgisPrint, HTMLStencilElement {
    }
    var HTMLArcgisPrintElement: {
        prototype: HTMLArcgisPrintElement;
        new (): HTMLArcgisPrintElement;
    };
    interface HTMLArcgisSearchElement extends Components.ArcgisSearch, HTMLStencilElement {
    }
    var HTMLArcgisSearchElement: {
        prototype: HTMLArcgisSearchElement;
        new (): HTMLArcgisSearchElement;
    };
    interface HTMLArcgisWebmapElement extends Components.ArcgisWebmap, HTMLStencilElement {
    }
    var HTMLArcgisWebmapElement: {
        prototype: HTMLArcgisWebmapElement;
        new (): HTMLArcgisWebmapElement;
    };
    interface HTMLArcgisWebsceneElement extends Components.ArcgisWebscene, HTMLStencilElement {
    }
    var HTMLArcgisWebsceneElement: {
        prototype: HTMLArcgisWebsceneElement;
        new (): HTMLArcgisWebsceneElement;
    };
    interface HTMLElementTagNameMap {
        "arcgis-basemap-gallery": HTMLArcgisBasemapGalleryElement;
        "arcgis-basemap-toggle": HTMLArcgisBasemapToggleElement;
        "arcgis-bookmarks": HTMLArcgisBookmarksElement;
        "arcgis-coordinate-conversion": HTMLArcgisCoordinateConversionElement;
        "arcgis-directions": HTMLArcgisDirectionsElement;
        "arcgis-editor": HTMLArcgisEditorElement;
        "arcgis-expand": HTMLArcgisExpandElement;
        "arcgis-feature-table": HTMLArcgisFeatureTableElement;
        "arcgis-layer-list": HTMLArcgisLayerListElement;
        "arcgis-legend": HTMLArcgisLegendElement;
        "arcgis-map": HTMLArcgisMapElement;
        "arcgis-portal": HTMLArcgisPortalElement;
        "arcgis-print": HTMLArcgisPrintElement;
        "arcgis-search": HTMLArcgisSearchElement;
        "arcgis-webmap": HTMLArcgisWebmapElement;
        "arcgis-webscene": HTMLArcgisWebsceneElement;
    }
}
declare namespace LocalJSX {
    interface ArcgisBasemapGallery {
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisBasemapToggle {
        "nextBasemap"?: string;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisBookmarks {
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisCoordinateConversion {
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisDirections {
        "apiKey"?: string;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisEditor {
        "allowedWorkflows"?: string;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisExpand {
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisFeatureTable {
        "fieldConfigs"?: any | string;
        "itemId"?: string;
        "layer"?: any;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "onRowSelectionChange"?: (event: CustomEvent<__esri.FeatureTableSelectionChangeEvent>) => void;
        "position"?: string;
        "url"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisLayerList {
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisLegend {
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisMap {
        "apiKey"?: string;
        "basemap"?: string;
        "center"?: number[] | string;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "view"?: __esri.MapView;
        "zoom"?: number;
    }
    interface ArcgisPortal {
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "portal"?: any;
        "url"?: string;
    }
    interface ArcgisPrint {
        "allowedFormats"?: string;
        "allowedLayouts"?: string;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisSearch {
        "onSearchBlur"?: (event: CustomEvent<__esri.SearchSearchBlurEvent>) => void;
        "onSearchClear"?: (event: CustomEvent<__esri.SearchSearchClearEvent>) => void;
        "onSearchComplete"?: (event: CustomEvent<__esri.SearchSearchCompleteEvent>) => void;
        "onSearchFocus"?: (event: CustomEvent<__esri.SearchSearchFocusEvent>) => void;
        "onSearchStart"?: (event: CustomEvent<__esri.SearchSearchStartEvent>) => void;
        "onSelectResult"?: (event: CustomEvent<__esri.SearchSelectResultEvent>) => void;
        "onSuggestComplete"?: (event: CustomEvent<__esri.SearchSuggestCompleteEvent>) => void;
        "onSuggestStart"?: (event: CustomEvent<__esri.SearchSuggestStartEvent>) => void;
        "position"?: string;
        "view"?: __esri.MapView | __esri.SceneView;
        "widget"?: any;
    }
    interface ArcgisWebmap {
        "apiKey"?: string;
        "center"?: number[] | string;
        "itemId"?: string;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "view"?: __esri.MapView;
        "zoom"?: number;
    }
    interface ArcgisWebscene {
        "apiKey"?: string;
        "center"?: number[] | string;
        "itemId"?: string;
        "onLoaded"?: (event: CustomEvent<boolean>) => void;
        "view"?: __esri.SceneView;
        "zoom"?: number;
    }
    interface IntrinsicElements {
        "arcgis-basemap-gallery": ArcgisBasemapGallery;
        "arcgis-basemap-toggle": ArcgisBasemapToggle;
        "arcgis-bookmarks": ArcgisBookmarks;
        "arcgis-coordinate-conversion": ArcgisCoordinateConversion;
        "arcgis-directions": ArcgisDirections;
        "arcgis-editor": ArcgisEditor;
        "arcgis-expand": ArcgisExpand;
        "arcgis-feature-table": ArcgisFeatureTable;
        "arcgis-layer-list": ArcgisLayerList;
        "arcgis-legend": ArcgisLegend;
        "arcgis-map": ArcgisMap;
        "arcgis-portal": ArcgisPortal;
        "arcgis-print": ArcgisPrint;
        "arcgis-search": ArcgisSearch;
        "arcgis-webmap": ArcgisWebmap;
        "arcgis-webscene": ArcgisWebscene;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "arcgis-basemap-gallery": LocalJSX.ArcgisBasemapGallery & JSXBase.HTMLAttributes<HTMLArcgisBasemapGalleryElement>;
            "arcgis-basemap-toggle": LocalJSX.ArcgisBasemapToggle & JSXBase.HTMLAttributes<HTMLArcgisBasemapToggleElement>;
            "arcgis-bookmarks": LocalJSX.ArcgisBookmarks & JSXBase.HTMLAttributes<HTMLArcgisBookmarksElement>;
            "arcgis-coordinate-conversion": LocalJSX.ArcgisCoordinateConversion & JSXBase.HTMLAttributes<HTMLArcgisCoordinateConversionElement>;
            "arcgis-directions": LocalJSX.ArcgisDirections & JSXBase.HTMLAttributes<HTMLArcgisDirectionsElement>;
            "arcgis-editor": LocalJSX.ArcgisEditor & JSXBase.HTMLAttributes<HTMLArcgisEditorElement>;
            "arcgis-expand": LocalJSX.ArcgisExpand & JSXBase.HTMLAttributes<HTMLArcgisExpandElement>;
            "arcgis-feature-table": LocalJSX.ArcgisFeatureTable & JSXBase.HTMLAttributes<HTMLArcgisFeatureTableElement>;
            "arcgis-layer-list": LocalJSX.ArcgisLayerList & JSXBase.HTMLAttributes<HTMLArcgisLayerListElement>;
            "arcgis-legend": LocalJSX.ArcgisLegend & JSXBase.HTMLAttributes<HTMLArcgisLegendElement>;
            "arcgis-map": LocalJSX.ArcgisMap & JSXBase.HTMLAttributes<HTMLArcgisMapElement>;
            "arcgis-portal": LocalJSX.ArcgisPortal & JSXBase.HTMLAttributes<HTMLArcgisPortalElement>;
            "arcgis-print": LocalJSX.ArcgisPrint & JSXBase.HTMLAttributes<HTMLArcgisPrintElement>;
            "arcgis-search": LocalJSX.ArcgisSearch & JSXBase.HTMLAttributes<HTMLArcgisSearchElement>;
            "arcgis-webmap": LocalJSX.ArcgisWebmap & JSXBase.HTMLAttributes<HTMLArcgisWebmapElement>;
            "arcgis-webscene": LocalJSX.ArcgisWebscene & JSXBase.HTMLAttributes<HTMLArcgisWebsceneElement>;
        }
    }
}
